name: daily_mendako
on:
  push:
    paths:
    - 'action.txt'
  schedule:
    # 更新時間
    #  5,  6,  7,  8,  9, 10, 11, 12, 13, 17, 18, 19, 20, 21, 22, 23 (JST, UTC+09)
    # 20, 21, 22, 23,  0,  1,  2,  3,  4,  8,  9, 10, 11, 12, 13, 14 (GMT)
    # デーモンプロセス設定 (世界標準時)
    - cron: 1 22 * * *

jobs:
  download-image:
    name: daily_mendako
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick pngquant advancecomp
      
      - name: set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      
      - name: install gem
        run: gem install twitter mini_magick
      
      - name: work
        run: ruby mendako.rb ${{secrets.TWITTER_CONSUMER_KEY}} ${{secrets.TWITTER_CONSUMER_SECRET}} ${{secrets.TWITTER_ACCESS_TOKEN}} ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
      
      ### DEPLOY ###
      # https://qiita.com/syui/items/f1f2db8660cda34d8938
      # https://github.com/peaceiris/actions-gh-pages
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public
